export const demoCategories = [
  {
    "category_id": 1,
    "name": "LLMs"
  },
  {
    "category_id": 2,
    "name": "Coding AI Models"
  },
  {
    "category_id": 3,
    "name": "Image Generation Models"
  },
  {
    "category_id": 4,
    "name": "Video Generation Models"
  },
  {
    "category_id": 5,
    "name": "Audio / Speech Models"
  },
  {
    "category_id": 6,
    "name": "Multimodal Models"
  },
  {
    "category_id": 7,
    "name": "Robotics / Agents"
  },
  {
    "category_id": 8,
    "name": "Data / Prediction Models"
  },
  {
    "category_id": 9,
    "name": "Specialized AI Models"
  }
]

export const demoTools = [
  {
    "model_id": 1,
    "name": "GPT-4",
    "description": "Advanced text generation and reasoning model from OpenAI.",
    "tags": "llm,text,reasoning,openai,gpt-4",
    "website_url": "https://openai.com/research/gpt-4",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fopenai.com%2Fresearch%2Fgpt-4",
    "is_free": 0,
    "avg_rating": 4.1,
    "category_id": 1,
    "category_name": "LLMs"
  },
  {
    "model_id": 2,
    "name": "GPT-5",
    "description": "Next-generation multimodal reasoning model from OpenAI.",
    "tags": "llm,multimodal,reasoning,openai,gpt-5",
    "website_url": "https://openai.com/gpt-5/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fopenai.com%2Fgpt-5%2F",
    "is_free": 0,
    "avg_rating": 4.2,
    "category_id": 1,
    "category_name": "LLMs"
  },
  {
    "model_id": 3,
    "name": "Claude 3 Opus",
    "description": "High-end Claude model for deep reasoning and long-context analysis.",
    "tags": "llm,reasoning,long-context,anthropic,claude",
    "website_url": "https://www.anthropic.com/news/claude-3-family",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fwww.anthropic.com%2Fnews%2Fclaude-3-family",
    "is_free": 0,
    "avg_rating": 4.3,
    "category_id": 1,
    "category_name": "LLMs"
  },
  {
    "model_id": 4,
    "name": "Claude 3 Sonnet",
    "description": "Balanced Claude model for everyday assistant and reasoning tasks.",
    "tags": "llm,assistant,balanced,anthropic,claude",
    "website_url": "https://www.anthropic.com/news/claude-3-family",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fwww.anthropic.com%2Fnews%2Fclaude-3-family",
    "is_free": 0,
    "avg_rating": 4.4,
    "category_id": 1,
    "category_name": "LLMs"
  },
  {
    "model_id": 5,
    "name": "Claude 3 Haiku",
    "description": "Fast lightweight Claude model for quick responses.",
    "tags": "llm,fast,lightweight,anthropic,claude",
    "website_url": "https://www.anthropic.com/news/claude-3-family",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fwww.anthropic.com%2Fnews%2Fclaude-3-family",
    "is_free": 0,
    "avg_rating": 4.5,
    "category_id": 1,
    "category_name": "LLMs"
  },
  {
    "model_id": 6,
    "name": "Gemini 1.5 Pro",
    "description": "Gemini model focused on multimodal understanding and long context.",
    "tags": "llm,multimodal,long-context,google,gemini",
    "website_url": "https://deepmind.google/models/gemini/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fdeepmind.google%2Fmodels%2Fgemini%2F",
    "is_free": 0,
    "avg_rating": 4.6,
    "category_id": 1,
    "category_name": "LLMs"
  },
  {
    "model_id": 7,
    "name": "Gemini 1.5 Flash",
    "description": "Fast Gemini model for lightweight assistant tasks.",
    "tags": "llm,fast,assistant,google,gemini",
    "website_url": "https://deepmind.google/models/gemini/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fdeepmind.google%2Fmodels%2Fgemini%2F",
    "is_free": 0,
    "avg_rating": 4.7,
    "category_id": 1,
    "category_name": "LLMs"
  },
  {
    "model_id": 8,
    "name": "LLaMA 3",
    "description": "Open-weight LLM family from Meta for general text reasoning.",
    "tags": "llm,open-source,meta,llama,reasoning",
    "website_url": "https://www.llama.com/llama3/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fwww.llama.com%2Fllama3%2F",
    "is_free": 1,
    "avg_rating": 4.8,
    "category_id": 1,
    "category_name": "LLMs"
  },
  {
    "model_id": 9,
    "name": "Mistral Large",
    "description": "High-performance large language model from Mistral.",
    "tags": "llm,mistral,reasoning,enterprise,large",
    "website_url": "https://mistral.ai/news/mistral-large/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fmistral.ai%2Fnews%2Fmistral-large%2F",
    "is_free": 0,
    "avg_rating": 4.9,
    "category_id": 1,
    "category_name": "LLMs"
  },
  {
    "model_id": 10,
    "name": "Mixtral 8x7B",
    "description": "Mixture-of-experts language model from Mistral.",
    "tags": "llm,moe,mistral,open-source,mixtral",
    "website_url": "https://mistral.ai/news/mixtral-of-experts/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fmistral.ai%2Fnews%2Fmixtral-of-experts%2F",
    "is_free": 1,
    "avg_rating": 4.1,
    "category_id": 1,
    "category_name": "LLMs"
  },
  {
    "model_id": 11,
    "name": "Falcon 180B",
    "description": "Large open-source language model from TII.",
    "tags": "llm,open-source,falcon,tii,large",
    "website_url": "https://falconllm.tii.ae/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Ffalconllm.tii.ae%2F",
    "is_free": 1,
    "avg_rating": 4.2,
    "category_id": 1,
    "category_name": "LLMs"
  },
  {
    "model_id": 12,
    "name": "Command R+",
    "description": "Enterprise conversational AI model from Cohere.",
    "tags": "llm,enterprise,cohere,conversational,rag",
    "website_url": "https://docs.cohere.com/docs/command-r-plus",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fdocs.cohere.com%2Fdocs%2Fcommand-r-plus",
    "is_free": 0,
    "avg_rating": 4.3,
    "category_id": 1,
    "category_name": "LLMs"
  },
  {
    "model_id": 13,
    "name": "Jurassic-2",
    "description": "NLP and text generation model family from AI21 Labs.",
    "tags": "llm,text-generation,ai21,jurassic,nlp",
    "website_url": "https://docs.ai21.com/docs/jurassic-2-models",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fdocs.ai21.com%2Fdocs%2Fjurassic-2-models",
    "is_free": 0,
    "avg_rating": 4.4,
    "category_id": 1,
    "category_name": "LLMs"
  },
  {
    "model_id": 14,
    "name": "BLOOM",
    "description": "Multilingual open large language model from BigScience.",
    "tags": "llm,multilingual,open-source,bloom,bigscience",
    "website_url": "https://huggingface.co/bigscience/bloom",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fhuggingface.co%2Fbigscience%2Fbloom",
    "is_free": 1,
    "avg_rating": 4.5,
    "category_id": 1,
    "category_name": "LLMs"
  },
  {
    "model_id": 15,
    "name": "PaLM 2",
    "description": "Google model for text reasoning and language tasks.",
    "tags": "llm,google,palm,text,reasoning",
    "website_url": "https://developers.googleblog.com/en/palm-2-api/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fdevelopers.googleblog.com%2Fen%2Fpalm-2-api%2F",
    "is_free": 0,
    "avg_rating": 4.6,
    "category_id": 1,
    "category_name": "LLMs"
  },
  {
    "model_id": 16,
    "name": "RWKV",
    "description": "RNN-style language model architecture with LLM behavior.",
    "tags": "llm,rnn,open-source,rwkv,text",
    "website_url": "https://www.rwkv.com/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fwww.rwkv.com%2F",
    "is_free": 1,
    "avg_rating": 4.7,
    "category_id": 1,
    "category_name": "LLMs"
  },
  {
    "model_id": 17,
    "name": "DeepSeek LLM",
    "description": "Reasoning and coding oriented LLM from DeepSeek.",
    "tags": "llm,reasoning,coding,deepseek,open-source",
    "website_url": "https://github.com/deepseek-ai/DeepSeek-LLM",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fgithub.com%2Fdeepseek-ai%2FDeepSeek-LLM",
    "is_free": 1,
    "avg_rating": 4.8,
    "category_id": 1,
    "category_name": "LLMs"
  },
  {
    "model_id": 18,
    "name": "Qwen 2",
    "description": "Alibaba open LLM family for multilingual reasoning.",
    "tags": "llm,qwen,alibaba,multilingual,open-source",
    "website_url": "https://qwenlm.github.io/blog/qwen2/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fqwenlm.github.io%2Fblog%2Fqwen2%2F",
    "is_free": 1,
    "avg_rating": 4.9,
    "category_id": 1,
    "category_name": "LLMs"
  },
  {
    "model_id": 19,
    "name": "Yi-34B",
    "description": "Chinese and English large model from 01.AI.",
    "tags": "llm,yi,01.ai,bilingual,open-source",
    "website_url": "https://www.01.ai/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fwww.01.ai%2F",
    "is_free": 1,
    "avg_rating": 4.1,
    "category_id": 1,
    "category_name": "LLMs"
  },
  {
    "model_id": 20,
    "name": "Orca",
    "description": "Reasoning-focused language model line from Microsoft Research.",
    "tags": "llm,reasoning,microsoft,orca,research",
    "website_url": "https://www.microsoft.com/en-us/research/blog/orca-2-teaching-small-language-models-how-to-reason/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fwww.microsoft.com%2Fen-us%2Fresearch%2Fblog%2Forca-2-teaching-small-language-models-how-to-reason%2F",
    "is_free": 1,
    "avg_rating": 4.2,
    "category_id": 1,
    "category_name": "LLMs"
  },
  {
    "model_id": 21,
    "name": "Codex",
    "description": "OpenAI coding agent for generation, editing, and software tasks.",
    "tags": "coding,agent,openai,codex,developer",
    "website_url": "https://openai.com/codex",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fopenai.com%2Fcodex",
    "is_free": 0,
    "avg_rating": 4.3,
    "category_id": 2,
    "category_name": "Coding AI Models"
  },
  {
    "model_id": 22,
    "name": "Code LLaMA",
    "description": "Code-focused large language model from Meta.",
    "tags": "coding,llama,meta,open-source,developer",
    "website_url": "https://www.llama.com/code-llama/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fwww.llama.com%2Fcode-llama%2F",
    "is_free": 1,
    "avg_rating": 4.4,
    "category_id": 2,
    "category_name": "Coding AI Models"
  },
  {
    "model_id": 23,
    "name": "DeepSeek-Coder",
    "description": "Coding and debugging model family from DeepSeek.",
    "tags": "coding,debugging,deepseek,open-source,developer",
    "website_url": "https://github.com/deepseek-ai/DeepSeek-Coder",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fgithub.com%2Fdeepseek-ai%2FDeepSeek-Coder",
    "is_free": 1,
    "avg_rating": 4.5,
    "category_id": 2,
    "category_name": "Coding AI Models"
  },
  {
    "model_id": 24,
    "name": "StarCoder",
    "description": "Open-source coding model from BigCode.",
    "tags": "coding,open-source,bigcode,starcoder,developer",
    "website_url": "https://huggingface.co/bigcode/starcoder",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fhuggingface.co%2Fbigcode%2Fstarcoder",
    "is_free": 1,
    "avg_rating": 4.6,
    "category_id": 2,
    "category_name": "Coding AI Models"
  },
  {
    "model_id": 25,
    "name": "WizardCoder",
    "description": "Instruction-tuned coding model for developer tasks.",
    "tags": "coding,instruction-tuned,wizardcoder,open-source,developer",
    "website_url": "https://wizardlm.github.io/WizardCoder/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fwizardlm.github.io%2FWizardCoder%2F",
    "is_free": 1,
    "avg_rating": 4.7,
    "category_id": 2,
    "category_name": "Coding AI Models"
  },
  {
    "model_id": 26,
    "name": "PolyCoder",
    "description": "Code generation model with a focus on C language tasks.",
    "tags": "coding,c-language,polycoder,open-source,developer",
    "website_url": "https://github.com/VHellendoorn/Code-LMs",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fgithub.com%2FVHellendoorn%2FCode-LMs",
    "is_free": 1,
    "avg_rating": 4.8,
    "category_id": 2,
    "category_name": "Coding AI Models"
  },
  {
    "model_id": 27,
    "name": "CodeGeeX",
    "description": "Multilingual coding AI assistant from THUDM.",
    "tags": "coding,multilingual,codegeex,assistant,developer",
    "website_url": "https://codegeex.cn/en-US",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fcodegeex.cn%2Fen-US",
    "is_free": 1,
    "avg_rating": 4.9,
    "category_id": 2,
    "category_name": "Coding AI Models"
  },
  {
    "model_id": 28,
    "name": "Replit Code AI",
    "description": "Replit developer assistant for coding and app building.",
    "tags": "coding,replit,assistant,developer,automation",
    "website_url": "https://replit.com/ai",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Freplit.com%2Fai",
    "is_free": 0,
    "avg_rating": 4.1,
    "category_id": 2,
    "category_name": "Coding AI Models"
  },
  {
    "model_id": 29,
    "name": "AlphaCode",
    "description": "DeepMind model for competitive programming and hard coding tasks.",
    "tags": "coding,competitive-programming,alphacode,deepmind,reasoning",
    "website_url": "https://deepmind.google/discover/blog/competitive-programming-with-alphacode/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fdeepmind.google%2Fdiscover%2Fblog%2Fcompetitive-programming-with-alphacode%2F",
    "is_free": 1,
    "avg_rating": 4.2,
    "category_id": 2,
    "category_name": "Coding AI Models"
  },
  {
    "model_id": 30,
    "name": "CodeT5",
    "description": "Code understanding and generation model from Salesforce.",
    "tags": "coding,code-understanding,codet5,salesforce,open-source",
    "website_url": "https://github.com/salesforce/CodeT5",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fgithub.com%2Fsalesforce%2FCodeT5",
    "is_free": 1,
    "avg_rating": 4.3,
    "category_id": 2,
    "category_name": "Coding AI Models"
  },
  {
    "model_id": 31,
    "name": "DALL·E 3",
    "description": "Text-to-image generation model from OpenAI.",
    "tags": "image,text-to-image,openai,dalle,art",
    "website_url": "https://openai.com/dall-e-3",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fopenai.com%2Fdall-e-3",
    "is_free": 0,
    "avg_rating": 4.4,
    "category_id": 3,
    "category_name": "Image Generation Models"
  },
  {
    "model_id": 32,
    "name": "Midjourney",
    "description": "Artistic image generation tool for stylized visuals.",
    "tags": "image,art,midjourney,design,creative",
    "website_url": "https://www.midjourney.com/home",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fwww.midjourney.com%2Fhome",
    "is_free": 0,
    "avg_rating": 4.5,
    "category_id": 3,
    "category_name": "Image Generation Models"
  },
  {
    "model_id": 33,
    "name": "Stable Diffusion",
    "description": "Open-source image generation model family from Stability AI.",
    "tags": "image,stable-diffusion,open-source,stability,art",
    "website_url": "https://stability.ai/stable-diffusion",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fstability.ai%2Fstable-diffusion",
    "is_free": 1,
    "avg_rating": 4.6,
    "category_id": 3,
    "category_name": "Image Generation Models"
  },
  {
    "model_id": 34,
    "name": "SDXL",
    "description": "High-quality image generation model in the Stable Diffusion line.",
    "tags": "image,sdxl,stable-diffusion,stability,art",
    "website_url": "https://stability.ai/news/stable-diffusion-xl-release",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fstability.ai%2Fnews%2Fstable-diffusion-xl-release",
    "is_free": 1,
    "avg_rating": 4.7,
    "category_id": 3,
    "category_name": "Image Generation Models"
  },
  {
    "model_id": 35,
    "name": "Imagen",
    "description": "Google photorealistic image generation model.",
    "tags": "image,imagen,google,photorealistic,art",
    "website_url": "https://deepmind.google/technologies/imagen-3/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fdeepmind.google%2Ftechnologies%2Fimagen-3%2F",
    "is_free": 0,
    "avg_rating": 4.8,
    "category_id": 3,
    "category_name": "Image Generation Models"
  },
  {
    "model_id": 36,
    "name": "Kandinsky",
    "description": "Creative image generation model family from AI Forever.",
    "tags": "image,kandinsky,open-source,creative,art",
    "website_url": "https://github.com/ai-forever/Kandinsky-2",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fgithub.com%2Fai-forever%2FKandinsky-2",
    "is_free": 1,
    "avg_rating": 4.9,
    "category_id": 3,
    "category_name": "Image Generation Models"
  },
  {
    "model_id": 37,
    "name": "Leonardo AI",
    "description": "Design-focused image generation platform.",
    "tags": "image,design,leonardo,creative,art",
    "website_url": "https://leonardo.ai",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fleonardo.ai",
    "is_free": 0,
    "avg_rating": 4.1,
    "category_id": 3,
    "category_name": "Image Generation Models"
  },
  {
    "model_id": 38,
    "name": "Firefly",
    "description": "Adobe generative image tool for creative workflows.",
    "tags": "image,adobe,firefly,design,creative",
    "website_url": "https://www.adobe.com/products/firefly.html",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fwww.adobe.com%2Fproducts%2Ffirefly.html",
    "is_free": 0,
    "avg_rating": 4.2,
    "category_id": 3,
    "category_name": "Image Generation Models"
  },
  {
    "model_id": 39,
    "name": "Playground AI",
    "description": "Image generation workspace for creative experiments.",
    "tags": "image,playground,creative,art,design",
    "website_url": "https://playground.com",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fplayground.com",
    "is_free": 1,
    "avg_rating": 4.3,
    "category_id": 3,
    "category_name": "Image Generation Models"
  },
  {
    "model_id": 40,
    "name": "DreamStudio",
    "description": "Official Stable Diffusion interface from Stability AI.",
    "tags": "image,dreamstudio,stable-diffusion,stability,art",
    "website_url": "https://dreamstudio.ai",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fdreamstudio.ai",
    "is_free": 0,
    "avg_rating": 4.4,
    "category_id": 3,
    "category_name": "Image Generation Models"
  },
  {
    "model_id": 41,
    "name": "Sora",
    "description": "Realistic video generation model from OpenAI.",
    "tags": "video,generation,openai,sora,motion",
    "website_url": "https://openai.com/sora",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fopenai.com%2Fsora",
    "is_free": 0,
    "avg_rating": 4.5,
    "category_id": 4,
    "category_name": "Video Generation Models"
  },
  {
    "model_id": 42,
    "name": "Runway Gen-2",
    "description": "Text-to-video generation model from Runway.",
    "tags": "video,generation,runway,gen-2,motion",
    "website_url": "https://runwayml.com",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Frunwayml.com",
    "is_free": 0,
    "avg_rating": 4.6,
    "category_id": 4,
    "category_name": "Video Generation Models"
  },
  {
    "model_id": 43,
    "name": "Pika Labs",
    "description": "AI video creation platform for prompt-based clips.",
    "tags": "video,generation,pika,animation,motion",
    "website_url": "https://pika.art",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fpika.art",
    "is_free": 0,
    "avg_rating": 4.7,
    "category_id": 4,
    "category_name": "Video Generation Models"
  },
  {
    "model_id": 44,
    "name": "Stable Video Diffusion",
    "description": "Open video generation model from Stability AI.",
    "tags": "video,generation,stable-video-diffusion,stability,open-source",
    "website_url": "https://stability.ai/news/stable-video-diffusion-open-ai-video-model",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fstability.ai%2Fnews%2Fstable-video-diffusion-open-ai-video-model",
    "is_free": 1,
    "avg_rating": 4.8,
    "category_id": 4,
    "category_name": "Video Generation Models"
  },
  {
    "model_id": 45,
    "name": "ModelScope",
    "description": "Text-to-video model and studio from ModelScope.",
    "tags": "video,generation,modelscope,text-to-video,open-source",
    "website_url": "https://modelscope.cn/studios/damo/Text-to-Video-Synthesis",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fmodelscope.cn%2Fstudios%2Fdamo%2FText-to-Video-Synthesis",
    "is_free": 1,
    "avg_rating": 4.9,
    "category_id": 4,
    "category_name": "Video Generation Models"
  },
  {
    "model_id": 46,
    "name": "VideoCrafter",
    "description": "Video synthesis model for prompt-based generation.",
    "tags": "video,generation,videocrafter,synthesis,open-source",
    "website_url": "https://ailab-cvc.github.io/videocrafter/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Failab-cvc.github.io%2Fvideocrafter%2F",
    "is_free": 1,
    "avg_rating": 4.1,
    "category_id": 4,
    "category_name": "Video Generation Models"
  },
  {
    "model_id": 47,
    "name": "Genmo",
    "description": "AI video creation platform for motion generation.",
    "tags": "video,generation,genmo,motion,creative",
    "website_url": "https://www.genmo.ai",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fwww.genmo.ai",
    "is_free": 0,
    "avg_rating": 4.2,
    "category_id": 4,
    "category_name": "Video Generation Models"
  },
  {
    "model_id": 48,
    "name": "Lumiere",
    "description": "Google video generation model for coherent motion.",
    "tags": "video,generation,lumiere,google,motion",
    "website_url": "https://lumiere-video.github.io",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Flumiere-video.github.io",
    "is_free": 1,
    "avg_rating": 4.3,
    "category_id": 4,
    "category_name": "Video Generation Models"
  },
  {
    "model_id": 49,
    "name": "Phenaki",
    "description": "Google research model for long video generation from text.",
    "tags": "video,generation,phenaki,google,long-form",
    "website_url": "https://research.google/blog/phenaki-variable-length-video-generation-from-open-domain-textual-descriptions/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fresearch.google%2Fblog%2Fphenaki-variable-length-video-generation-from-open-domain-textual-descriptions%2F",
    "is_free": 1,
    "avg_rating": 4.4,
    "category_id": 4,
    "category_name": "Video Generation Models"
  },
  {
    "model_id": 50,
    "name": "AnimateDiff",
    "description": "Animation generation workflow built on diffusion models.",
    "tags": "video,animation,animatediff,diffusion,open-source",
    "website_url": "https://animatediff.github.io/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fanimatediff.github.io%2F",
    "is_free": 1,
    "avg_rating": 4.5,
    "category_id": 4,
    "category_name": "Video Generation Models"
  },
  {
    "model_id": 51,
    "name": "Whisper",
    "description": "Speech-to-text model from OpenAI.",
    "tags": "audio,speech-to-text,whisper,openai,transcription",
    "website_url": "https://openai.com/research/whisper",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fopenai.com%2Fresearch%2Fwhisper",
    "is_free": 1,
    "avg_rating": 4.6,
    "category_id": 5,
    "category_name": "Audio / Speech Models"
  },
  {
    "model_id": 52,
    "name": "VALL-E",
    "description": "Voice cloning model family from Microsoft Research.",
    "tags": "audio,voice-cloning,vall-e,microsoft,speech",
    "website_url": "https://www.microsoft.com/en-us/research/project/vall-e-x/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fwww.microsoft.com%2Fen-us%2Fresearch%2Fproject%2Fvall-e-x%2F",
    "is_free": 1,
    "avg_rating": 4.7,
    "category_id": 5,
    "category_name": "Audio / Speech Models"
  },
  {
    "model_id": 53,
    "name": "Bark",
    "description": "Text-to-speech model from Suno.",
    "tags": "audio,text-to-speech,bark,suno,voice",
    "website_url": "https://github.com/suno-ai/bark",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fgithub.com%2Fsuno-ai%2Fbark",
    "is_free": 1,
    "avg_rating": 4.8,
    "category_id": 5,
    "category_name": "Audio / Speech Models"
  },
  {
    "model_id": 54,
    "name": "Tacotron 2",
    "description": "Speech synthesis model from NVIDIA.",
    "tags": "audio,speech-synthesis,tacotron,nvidia,voice",
    "website_url": "https://github.com/NVIDIA/tacotron2",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fgithub.com%2FNVIDIA%2Ftacotron2",
    "is_free": 1,
    "avg_rating": 4.9,
    "category_id": 5,
    "category_name": "Audio / Speech Models"
  },
  {
    "model_id": 55,
    "name": "WaveNet",
    "description": "DeepMind model for realistic voice generation.",
    "tags": "audio,wavenet,deepmind,voice,generation",
    "website_url": "https://deepmind.google/discover/blog/wavenet-a-generative-model-for-raw-audio/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fdeepmind.google%2Fdiscover%2Fblog%2Fwavenet-a-generative-model-for-raw-audio%2F",
    "is_free": 1,
    "avg_rating": 4.1,
    "category_id": 5,
    "category_name": "Audio / Speech Models"
  },
  {
    "model_id": 56,
    "name": "ElevenLabs AI",
    "description": "Voice generation and dubbing platform from ElevenLabs.",
    "tags": "audio,voice,elevenlabs,dubbing,speech",
    "website_url": "https://elevenlabs.io",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Felevenlabs.io",
    "is_free": 0,
    "avg_rating": 4.2,
    "category_id": 5,
    "category_name": "Audio / Speech Models"
  },
  {
    "model_id": 57,
    "name": "AudioLM",
    "description": "Google model for generating coherent audio from prompts.",
    "tags": "audio,audiolm,google,generation,speech",
    "website_url": "https://google-research.github.io/seanet/audiolm/examples/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fgoogle-research.github.io%2Fseanet%2Faudiolm%2Fexamples%2F",
    "is_free": 1,
    "avg_rating": 4.3,
    "category_id": 5,
    "category_name": "Audio / Speech Models"
  },
  {
    "model_id": 58,
    "name": "MusicLM",
    "description": "Google model for music generation from text.",
    "tags": "audio,musiclm,google,music,generation",
    "website_url": "https://google-research.github.io/seanet/musiclm/examples/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fgoogle-research.github.io%2Fseanet%2Fmusiclm%2Fexamples%2F",
    "is_free": 1,
    "avg_rating": 4.4,
    "category_id": 5,
    "category_name": "Audio / Speech Models"
  },
  {
    "model_id": 59,
    "name": "Riffusion",
    "description": "Music loop generation tool using diffusion models.",
    "tags": "audio,music,riffusion,loops,generation",
    "website_url": "https://www.riffusion.com",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fwww.riffusion.com",
    "is_free": 1,
    "avg_rating": 4.5,
    "category_id": 5,
    "category_name": "Audio / Speech Models"
  },
  {
    "model_id": 60,
    "name": "SoundStorm",
    "description": "Google audio synthesis model for fast waveform generation.",
    "tags": "audio,soundstorm,google,synthesis,voice",
    "website_url": "https://google-research.github.io/seanet/soundstorm/examples/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fgoogle-research.github.io%2Fseanet%2Fsoundstorm%2Fexamples%2F",
    "is_free": 1,
    "avg_rating": 4.6,
    "category_id": 5,
    "category_name": "Audio / Speech Models"
  },
  {
    "model_id": 61,
    "name": "GPT-4o",
    "description": "OpenAI multimodal model for text, image, and audio tasks.",
    "tags": "multimodal,gpt-4o,openai,text,image,audio",
    "website_url": "https://openai.com/index/hello-gpt-4o/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fopenai.com%2Findex%2Fhello-gpt-4o%2F",
    "is_free": 0,
    "avg_rating": 4.7,
    "category_id": 6,
    "category_name": "Multimodal Models"
  },
  {
    "model_id": 62,
    "name": "Gemini Ultra",
    "description": "Advanced multimodal Gemini model from Google.",
    "tags": "multimodal,gemini,google,reasoning,image",
    "website_url": "https://deepmind.google/technologies/gemini/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fdeepmind.google%2Ftechnologies%2Fgemini%2F",
    "is_free": 0,
    "avg_rating": 4.8,
    "category_id": 6,
    "category_name": "Multimodal Models"
  },
  {
    "model_id": 63,
    "name": "Kosmos-2",
    "description": "Vision and language model from Microsoft Research.",
    "tags": "multimodal,vision-language,kosmos,microsoft,image",
    "website_url": "https://www.microsoft.com/en-us/research/project/kosmos-2/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fwww.microsoft.com%2Fen-us%2Fresearch%2Fproject%2Fkosmos-2%2F",
    "is_free": 1,
    "avg_rating": 4.9,
    "category_id": 6,
    "category_name": "Multimodal Models"
  },
  {
    "model_id": 64,
    "name": "Flamingo",
    "description": "Image understanding model from DeepMind.",
    "tags": "multimodal,vision-language,flamingo,deepmind,image",
    "website_url": "https://deepmind.google/discover/blog/tackling-multiple-tasks-with-a-single-visual-language-model/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fdeepmind.google%2Fdiscover%2Fblog%2Ftackling-multiple-tasks-with-a-single-visual-language-model%2F",
    "is_free": 1,
    "avg_rating": 4.1,
    "category_id": 6,
    "category_name": "Multimodal Models"
  },
  {
    "model_id": 65,
    "name": "Gato",
    "description": "Generalist multimodal agent from DeepMind.",
    "tags": "multimodal,gato,deepmind,generalist,agent",
    "website_url": "https://deepmind.google/discover/blog/a-generalist-agent/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fdeepmind.google%2Fdiscover%2Fblog%2Fa-generalist-agent%2F",
    "is_free": 1,
    "avg_rating": 4.2,
    "category_id": 6,
    "category_name": "Multimodal Models"
  },
  {
    "model_id": 66,
    "name": "Visual ChatGPT",
    "description": "Image and text interaction system from Microsoft.",
    "tags": "multimodal,visual-chatgpt,microsoft,image,text",
    "website_url": "https://github.com/microsoft/visual-chatgpt",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvisual-chatgpt",
    "is_free": 1,
    "avg_rating": 4.3,
    "category_id": 6,
    "category_name": "Multimodal Models"
  },
  {
    "model_id": 67,
    "name": "ImageBind",
    "description": "Meta model for binding multiple sensory inputs.",
    "tags": "multimodal,imagebind,meta,image,audio",
    "website_url": "https://imagebind.metademolab.com/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fimagebind.metademolab.com%2F",
    "is_free": 1,
    "avg_rating": 4.4,
    "category_id": 6,
    "category_name": "Multimodal Models"
  },
  {
    "model_id": 68,
    "name": "BLIP-2",
    "description": "Vision-language model for image understanding and captioning.",
    "tags": "multimodal,blip-2,vision-language,salesforce,image",
    "website_url": "https://github.com/salesforce/LAVIS/tree/main/projects/blip2",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fgithub.com%2Fsalesforce%2FLAVIS%2Ftree%2Fmain%2Fprojects%2Fblip2",
    "is_free": 1,
    "avg_rating": 4.5,
    "category_id": 6,
    "category_name": "Multimodal Models"
  },
  {
    "model_id": 69,
    "name": "CLIP",
    "description": "OpenAI model for image-text understanding.",
    "tags": "multimodal,clip,openai,image,text",
    "website_url": "https://openai.com/research/clip",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fopenai.com%2Fresearch%2Fclip",
    "is_free": 1,
    "avg_rating": 4.6,
    "category_id": 6,
    "category_name": "Multimodal Models"
  },
  {
    "model_id": 70,
    "name": "ALIGN",
    "description": "Google image-text alignment model.",
    "tags": "multimodal,align,google,image,text",
    "website_url": "https://research.google/pubs/align-scaling-up-visual-and-vision-language-representation-learning-with-noisy-text-supervision/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fresearch.google%2Fpubs%2Falign-scaling-up-visual-and-vision-language-representation-learning-with-noisy-text-supervision%2F",
    "is_free": 1,
    "avg_rating": 4.7,
    "category_id": 6,
    "category_name": "Multimodal Models"
  },
  {
    "model_id": 71,
    "name": "RT-2",
    "description": "Robot reasoning model that maps vision and language into actions.",
    "tags": "robotics,rt-2,deepmind,vision,action",
    "website_url": "https://deepmind.google/discover/blog/rt-2-new-model-translates-vision-and-language-into-action/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fdeepmind.google%2Fdiscover%2Fblog%2Frt-2-new-model-translates-vision-and-language-into-action%2F",
    "is_free": 1,
    "avg_rating": 4.8,
    "category_id": 7,
    "category_name": "Robotics / Agents"
  },
  {
    "model_id": 72,
    "name": "AutoGPT",
    "description": "Autonomous agent framework for long task automation.",
    "tags": "agents,autogpt,automation,open-source,task-execution",
    "website_url": "https://agpt.co",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fagpt.co",
    "is_free": 1,
    "avg_rating": 4.9,
    "category_id": 7,
    "category_name": "Robotics / Agents"
  },
  {
    "model_id": 73,
    "name": "BabyAGI",
    "description": "Task automation agent framework for autonomous planning.",
    "tags": "agents,babyagi,automation,planning,open-source",
    "website_url": "https://babyagi.org",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fbabyagi.org",
    "is_free": 1,
    "avg_rating": 4.1,
    "category_id": 7,
    "category_name": "Robotics / Agents"
  },
  {
    "model_id": 74,
    "name": "Voyager",
    "description": "Minecraft autonomous AI agent from the Voyager project.",
    "tags": "agents,voyager,minecraft,autonomous,reasoning",
    "website_url": "https://voyager.minedojo.org/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fvoyager.minedojo.org%2F",
    "is_free": 1,
    "avg_rating": 4.2,
    "category_id": 7,
    "category_name": "Robotics / Agents"
  },
  {
    "model_id": 75,
    "name": "OpenAI Operator",
    "description": "OpenAI agent for taking actions on the web.",
    "tags": "agents,operator,openai,web,automation",
    "website_url": "https://openai.com/index/introducing-operator/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fopenai.com%2Findex%2Fintroducing-operator%2F",
    "is_free": 0,
    "avg_rating": 4.3,
    "category_id": 7,
    "category_name": "Robotics / Agents"
  },
  {
    "model_id": 76,
    "name": "Meta AI Habitat",
    "description": "Embodied AI platform for simulated robotics environments.",
    "tags": "robotics,habitat,meta,embodied-ai,simulation",
    "website_url": "https://aihabitat.org/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Faihabitat.org%2F",
    "is_free": 1,
    "avg_rating": 4.4,
    "category_id": 7,
    "category_name": "Robotics / Agents"
  },
  {
    "model_id": 77,
    "name": "SayCan",
    "description": "Robot decision-making system from Google Research.",
    "tags": "robotics,saycan,google,decision-making,planning",
    "website_url": "https://say-can.github.io/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fsay-can.github.io%2F",
    "is_free": 1,
    "avg_rating": 4.5,
    "category_id": 7,
    "category_name": "Robotics / Agents"
  },
  {
    "model_id": 78,
    "name": "RoboCat",
    "description": "Self-improving robotic learning agent from DeepMind.",
    "tags": "robotics,robocat,deepmind,learning,agent",
    "website_url": "https://deepmind.google/discover/blog/robocat-a-self-improving-robotic-agent/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fdeepmind.google%2Fdiscover%2Fblog%2Frobocat-a-self-improving-robotic-agent%2F",
    "is_free": 1,
    "avg_rating": 4.6,
    "category_id": 7,
    "category_name": "Robotics / Agents"
  },
  {
    "model_id": 79,
    "name": "PaLM-E",
    "description": "Robot and vision model for embodied tasks.",
    "tags": "robotics,palm-e,vision,embodied-ai,google",
    "website_url": "https://palm-e.github.io/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fpalm-e.github.io%2F",
    "is_free": 1,
    "avg_rating": 4.7,
    "category_id": 7,
    "category_name": "Robotics / Agents"
  },
  {
    "model_id": 80,
    "name": "ACT-1",
    "description": "Humanoid control and action model from Adept.",
    "tags": "robotics,act-1,adept,agents,control",
    "website_url": "https://www.adept.ai/blog/act-1",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fwww.adept.ai%2Fblog%2Fact-1",
    "is_free": 0,
    "avg_rating": 4.8,
    "category_id": 7,
    "category_name": "Robotics / Agents"
  },
  {
    "model_id": 81,
    "name": "XGBoost",
    "description": "Structured data prediction model using gradient boosting.",
    "tags": "data,prediction,xgboost,boosting,ml",
    "website_url": "https://xgboost.readthedocs.io/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fxgboost.readthedocs.io%2F",
    "is_free": 1,
    "avg_rating": 4.9,
    "category_id": 8,
    "category_name": "Data / Prediction Models"
  },
  {
    "model_id": 82,
    "name": "LightGBM",
    "description": "Gradient boosting framework optimized for speed.",
    "tags": "data,prediction,lightgbm,boosting,ml",
    "website_url": "https://lightgbm.readthedocs.io/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Flightgbm.readthedocs.io%2F",
    "is_free": 1,
    "avg_rating": 4.1,
    "category_id": 8,
    "category_name": "Data / Prediction Models"
  },
  {
    "model_id": 83,
    "name": "CatBoost",
    "description": "Gradient boosting model with strong categorical feature support.",
    "tags": "data,prediction,catboost,boosting,ml",
    "website_url": "https://catboost.ai/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fcatboost.ai%2F",
    "is_free": 1,
    "avg_rating": 4.2,
    "category_id": 8,
    "category_name": "Data / Prediction Models"
  },
  {
    "model_id": 84,
    "name": "Prophet",
    "description": "Time-series forecasting library from Meta.",
    "tags": "data,prediction,prophet,time-series,forecasting",
    "website_url": "https://facebook.github.io/prophet/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Ffacebook.github.io%2Fprophet%2F",
    "is_free": 1,
    "avg_rating": 4.3,
    "category_id": 8,
    "category_name": "Data / Prediction Models"
  },
  {
    "model_id": 85,
    "name": "ARIMA",
    "description": "Statistical forecasting model for time-series analysis.",
    "tags": "data,prediction,arima,time-series,forecasting",
    "website_url": "https://www.statsmodels.org/stable/generated/statsmodels.tsa.arima.model.ARIMA.html",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fwww.statsmodels.org%2Fstable%2Fgenerated%2Fstatsmodels.tsa.arima.model.ARIMA.html",
    "is_free": 1,
    "avg_rating": 4.4,
    "category_id": 8,
    "category_name": "Data / Prediction Models"
  },
  {
    "model_id": 86,
    "name": "BERT",
    "description": "Transformer model for NLP understanding tasks.",
    "tags": "data,nlp,bert,google,understanding",
    "website_url": "https://research.google/pubs/bert-pre-training-of-deep-bidirectional-transformers-for-language-understanding/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fresearch.google%2Fpubs%2Fbert-pre-training-of-deep-bidirectional-transformers-for-language-understanding%2F",
    "is_free": 1,
    "avg_rating": 4.5,
    "category_id": 8,
    "category_name": "Data / Prediction Models"
  },
  {
    "model_id": 87,
    "name": "RoBERTa",
    "description": "Improved BERT-style language model from Meta.",
    "tags": "data,nlp,roberta,meta,understanding",
    "website_url": "https://ai.meta.com/blog/roberta-an-optimized-method-for-pretraining-self-supervised-nlp-systems/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fai.meta.com%2Fblog%2Froberta-an-optimized-method-for-pretraining-self-supervised-nlp-systems%2F",
    "is_free": 1,
    "avg_rating": 4.6,
    "category_id": 8,
    "category_name": "Data / Prediction Models"
  },
  {
    "model_id": 88,
    "name": "DistilBERT",
    "description": "Lightweight distilled BERT model for NLP tasks.",
    "tags": "data,nlp,distilbert,huggingface,lightweight",
    "website_url": "https://huggingface.co/distilbert/distilbert-base-uncased",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fhuggingface.co%2Fdistilbert%2Fdistilbert-base-uncased",
    "is_free": 1,
    "avg_rating": 4.7,
    "category_id": 8,
    "category_name": "Data / Prediction Models"
  },
  {
    "model_id": 89,
    "name": "T5",
    "description": "Text-to-text transformer model from Google.",
    "tags": "data,nlp,t5,google,text-to-text",
    "website_url": "https://research.google/blog/exploring-transfer-learning-with-t5-the-text-to-text-transfer-transformer/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fresearch.google%2Fblog%2Fexploring-transfer-learning-with-t5-the-text-to-text-transfer-transformer%2F",
    "is_free": 1,
    "avg_rating": 4.8,
    "category_id": 8,
    "category_name": "Data / Prediction Models"
  },
  {
    "model_id": 90,
    "name": "ELECTRA",
    "description": "Efficient NLP pretraining approach from Google Research.",
    "tags": "data,nlp,electra,google,training",
    "website_url": "https://research.google/pubs/electra-pre-training-text-encoders-as-discriminators-rather-than-generators/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fresearch.google%2Fpubs%2Felectra-pre-training-text-encoders-as-discriminators-rather-than-generators%2F",
    "is_free": 1,
    "avg_rating": 4.9,
    "category_id": 8,
    "category_name": "Data / Prediction Models"
  },
  {
    "model_id": 91,
    "name": "AlphaFold",
    "description": "Protein structure prediction model from DeepMind.",
    "tags": "specialized,alphafold,biology,protein,deepmind",
    "website_url": "https://alphafold.ebi.ac.uk/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Falphafold.ebi.ac.uk%2F",
    "is_free": 1,
    "avg_rating": 4.1,
    "category_id": 9,
    "category_name": "Specialized AI Models"
  },
  {
    "model_id": 92,
    "name": "AlphaZero",
    "description": "Game-playing reinforcement learning system from DeepMind.",
    "tags": "specialized,alphazero,games,reinforcement-learning,deepmind",
    "website_url": "https://deepmind.google/discover/blog/alphazero-shedding-new-light-on-chess-shogi-and-go/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fdeepmind.google%2Fdiscover%2Fblog%2Falphazero-shedding-new-light-on-chess-shogi-and-go%2F",
    "is_free": 1,
    "avg_rating": 4.2,
    "category_id": 9,
    "category_name": "Specialized AI Models"
  },
  {
    "model_id": 93,
    "name": "MuZero",
    "description": "Model-based reinforcement learning system from DeepMind.",
    "tags": "specialized,muzero,reinforcement-learning,games,deepmind",
    "website_url": "https://deepmind.google/discover/blog/muzero-mastering-go-chess-shogi-and-atari-without-rules/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fdeepmind.google%2Fdiscover%2Fblog%2Fmuzero-mastering-go-chess-shogi-and-atari-without-rules%2F",
    "is_free": 1,
    "avg_rating": 4.3,
    "category_id": 9,
    "category_name": "Specialized AI Models"
  },
  {
    "model_id": 94,
    "name": "DeepSpeech",
    "description": "Speech recognition engine originally from Mozilla.",
    "tags": "specialized,deepspeech,speech-recognition,mozilla,audio",
    "website_url": "https://github.com/mozilla/DeepSpeech",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fgithub.com%2Fmozilla%2FDeepSpeech",
    "is_free": 1,
    "avg_rating": 4.4,
    "category_id": 9,
    "category_name": "Specialized AI Models"
  },
  {
    "model_id": 95,
    "name": "SAM (Segment Anything)",
    "description": "Image segmentation model from Meta AI.",
    "tags": "specialized,sam,segmentation,meta,vision",
    "website_url": "https://segment-anything.com/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fsegment-anything.com%2F",
    "is_free": 1,
    "avg_rating": 4.5,
    "category_id": 9,
    "category_name": "Specialized AI Models"
  },
  {
    "model_id": 96,
    "name": "ControlNet",
    "description": "Image conditioning model for controlled diffusion generation.",
    "tags": "specialized,controlnet,image,conditioning,diffusion",
    "website_url": "https://github.com/lllyasviel/ControlNet",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fgithub.com%2Flllyasviel%2FControlNet",
    "is_free": 1,
    "avg_rating": 4.6,
    "category_id": 9,
    "category_name": "Specialized AI Models"
  },
  {
    "model_id": 97,
    "name": "NeRF",
    "description": "Neural radiance field approach for 3D scene generation.",
    "tags": "specialized,nerf,3d,scene-generation,vision",
    "website_url": "https://www.matthewtancik.com/nerf",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fwww.matthewtancik.com%2Fnerf",
    "is_free": 1,
    "avg_rating": 4.7,
    "category_id": 9,
    "category_name": "Specialized AI Models"
  },
  {
    "model_id": 98,
    "name": "DreamFusion",
    "description": "Text-to-3D generation approach from Google.",
    "tags": "specialized,dreamfusion,3d,text-to-3d,google",
    "website_url": "https://dreamfusion3d.github.io/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fdreamfusion3d.github.io%2F",
    "is_free": 1,
    "avg_rating": 4.8,
    "category_id": 9,
    "category_name": "Specialized AI Models"
  },
  {
    "model_id": 99,
    "name": "Point-E",
    "description": "OpenAI system for generating 3D point clouds.",
    "tags": "specialized,point-e,3d,point-cloud,openai",
    "website_url": "https://openai.com/research/point-e",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fopenai.com%2Fresearch%2Fpoint-e",
    "is_free": 1,
    "avg_rating": 4.9,
    "category_id": 9,
    "category_name": "Specialized AI Models"
  },
  {
    "model_id": 100,
    "name": "GraphCast",
    "description": "Weather prediction model from Google DeepMind.",
    "tags": "specialized,graphcast,weather,prediction,deepmind",
    "website_url": "https://deepmind.google/science/graphcast/",
    "logo_url": "https://www.google.com/s2/favicons?sz=128&domain_url=https%3A%2F%2Fdeepmind.google%2Fscience%2Fgraphcast%2F",
    "is_free": 1,
    "avg_rating": 4.1,
    "category_id": 9,
    "category_name": "Specialized AI Models"
  }
]

export const demoStarterPrompts = [
  "I need the best AI tools for building a university project website.",
  "What should I use for coding, UI design, and deployment together?",
  "Recommend the strongest tools for video generation and dubbing.",
  "I want a multimodal model for research, screenshots, and long context.",
  "Which image tools are best for logos, posters, and social content?"
]
